Form collaboration
tnyandoro/intuit-mint-clone pull request #2
Opened 2020-08-26 13:31 UTC by tahiry-dev

Our first pull request for the project HTML FORM

2020-08-26 16:57 UTC, Spayco requested changes
# Changes Requested 

Hello Team! 👋 

Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

* [ ] Files not related to the project should not be committed and added to .gitignore (e.g. `.`) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

- **I attached more required changes below**



### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-08-26 16:57 UTC, Spayco commented on index.html
> +          ><img class="mint-logo" src="images/mint_logo.png" alt="mint"
* [ ] It shows the Mint logo and text (logo on the left, text on the right) ([link to page](https://accounts.intuit.com/signup.html))

2020-08-26 16:57 UTC, Spayco commented on index.html
> +        /></a>
* [ ] It shows the Quickbooks logo and text (logo on the left, text on the right) ([link to page](https://accounts.intuit.com/signup.html))

2020-08-26 16:57 UTC, Spayco commented on index.html
> +        /></a>
* [ ] It shows the Turbotax logo and text (logo on the left, text on the right) ([link to page](https://accounts.intuit.com/signup.html))

2020-08-27 11:57 UTC, expjazz requested changes
## Status: Changes Required :recycle: 

Great work on this project :100: 

However, you did not set up a linter. I'm sorry that this was not previously mentioned in the last review, but this is quite important for your future projects. Please exercise patience :pray: 

- [ ] You need to set up GitHub actions as a linter

- [ ] Also, remove the readme from the git ignore, and also delete that unnecessary notes.txt

For more info, check [here](https://github.com/microverseinc/linters-config/tree/master/html-css)

### Please make the required changes and resubmit for a new code review once you are ready
Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-08-27 14:26 UTC, elmejdki requested changes
# status: require changes :recycle: 
## Great job so far team :clap: :+1: :100: but you need to make some minor changes :hammer: :wrench: :toolbox:  in order to get your project approved :checkered_flag: 

- [ ] Fix the linter errors:
![image](https://user-images.githubusercontent.com/34653764/91454615-1a690b00-e879-11ea-98eb-2d95331e733f.png)

- [ ] Remove README.md from the .gitignore file.

- [ ] Give to your form a fixed width instead of percentages.

### Please make all the required changes before you submit another code review.
## Happy Coding :tophat:

2020-08-28 06:35 UTC, Spayco approved these changes
# Project Approved ✔️ 

thank you for making the required changes, your project is now approved! 

### please don't forget to merge to master, good luck with the next projects!


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-08-28 07:47 UTC, merged